version: '3.9'
services:
  neo4j:
    image: neo4j:5.3
    ports: 
        - 7474:7474
        - 7687:7687
    # mounting a named volume to the container to track db data
    # volumes:
    #     - neo4j_data:/data/
    environment:
      NEO4J_AUTH: "neo4j/password"

