packages:
  - apps/*
  - packages/*

catalog:
  "@lorenzopant/tmdb": 1.22.1
  "@types/node": 25.8.0
  "@upstash/qstash": 2.11.0
  drizzle-orm: 0.45.2
  eslint-plugin-react-hooks: 7.1.1
  ts-pattern: 5.9.0
  typescript: 6.0.3
  zod: 4.3.6

catalogs:
  better-auth:
    "@better-auth/expo": 1.6.5
    better-auth: 1.6.5
  react:
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    react: 19.2.5
    react-dom: 19.2.5
  trpc:
    "@tanstack/react-query": 5.100.10
    "@trpc/client": 11.17.0
    "@trpc/react-query": 11.17.0
    "@trpc/server": 11.17.0
    superjson: 2.2.6

allowBuilds:
  "@prisma/engines": false
  "@sentry/cli": true
  core-js: false
  esbuild: false
  msw: false
  prisma: false
  protobufjs: false
  sharp: false
