packages:
  - apps/*
  - packages/*

catalog:
  "@lorenzopant/tmdb": 1.9.0
  "@types/node": 25.3.5
  drizzle-orm: 0.45.1
  eslint-plugin-react-hooks: 7.0.1
  ts-pattern: 5.9.0
  typescript: 5.9.3
  zod: 4.3.6

catalogs:
  better-auth:
    "@better-auth/expo": 1.5.4
    better-auth: 1.5.4
  react:
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    react: 19.2.0
    react-dom: 19.2.0
  trpc:
    "@tanstack/react-query": 5.90.21
    "@trpc/client": 11.12.0
    "@trpc/react-query": 11.12.0
    "@trpc/server": 11.12.0
    superjson: 2.2.6

ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - "@sentry/cli"
